# Data Cleaning and Preparation

### Loading in Finalized Datasets

In [44]:
import pandas as pd

In [45]:
listings = pd.read_csv("listings_with_rates.csv")
sold = pd.read_csv("sold_with_rates.csv")

C:\Users\mukun\AppData\Local\Temp\ipykernel_31584\1496518169.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  listings = pd.read_csv("listings_with_rates.csv")
C:\Users\mukun\AppData\Local\Temp\ipykernel_31584\1496518169.py:2: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sold = pd.read_csv("sold_with_rates.csv")

### Converting Relevant Fields to Date-Time Format

In [46]:
listings.columns

Index(['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency',
       'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor',
       'TaxAnnualAmount', 'CountyOrParish', 'PropertyType.1', 'MlsStatus',
       'ElementarySchool', 'ListAgentFirstName.1', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1',
       'StreetNumberNumeric', 'LivingArea.1', 'ListingId',
       'BathroomsTotalInteger', 'City', 'TaxYear', 'BuildingAreaTotal',
       'BedroomsTotal', 'ContractStatusChangeDate', 'Longitude.1',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'Latitude.1', 'ListPrice.1', 'StateOrProvince',
       'CoveredSpaces', 'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories',
       'HighSchool', 'Levels', 'ListAgentLastName.1', 'CloseDate.1',
       'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1', 'year_month',
       'rate_30yr_fixed'],
      dtype='object')

In [47]:
listings["CloseDate"] = pd.to_datetime(listings["CloseDate"])
listings["PurchaseContractDate"] = pd.to_datetime(listings["PurchaseContractDate"])
listings["ListingContractDate"] = pd.to_datetime(listings["ListingContractDate"])

In [48]:
sold.columns

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName', 'year_month',
       'rate_30yr_fixed'],
      dtype='object')

In [49]:
sold["CloseDate"] = pd.to_datetime(sold["CloseDate"])
sold["PurchaseContractDate"] = pd.to_datetime(sold["PurchaseContractDate"])
sold["ListingContractDate"] = pd.to_datetime(sold["ListingContractDate"])

### Validating Logical Order of Date Fields

#### Flagging in Listing Dataset

In [50]:
listings["listings_after_close_flag"] = listings["ListingContractDate"] > listings["PurchaseContractDate"]

In [51]:
listings[listings["listings_after_close_flag"] == True].head()

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,year_month,rate_30yr_fixed,listings_after_close_flag
1063,609000.0,1154142014,axe@realestatewithaxe.com,2026-02-26,609000.0,Matthew,Axelson,32.826065,-117.172480,5938 Chandler Dr,...,NaN,92117,Compass,NaN,7200.0,NaN,5938 Chandler Dr,2026-02,6.0475,True
4439,755000.0,1153525823,spencersmock@whisselrealty.com,2026-02-20,755000.0,Spencer,Smock,32.856760,-117.233099,3270 Via Marin 48,...,NaN,92037,Compass,350.0,109883.0,NaN,3270 Via Marin 48,2026-02,6.0475,True
8003,4200000.0,1153248885,tim@timvandamm.com,2026-02-19,4200000.0,Tim,Van Damm,32.970404,-117.219876,4631 Rancho Laguna Bend,...,NaN,92130,Compass,800.0,22215.0,NaN,4631 Rancho Laguna Bend,2026-02,6.0475,True
8963,1625000.0,1153186301,brian@gravergroup.com,2026-02-18,1625000.0,Brian,Graver,34.196837,-118.848509,1662 E Janss Road,...,NaN,91362,Redfin Corporation,NaN,25700.0,NaN,1662 E Janss Road,2026-02,6.0475,True
11522,4200000.0,1153005475,gregg@lajollarealestateagent.com,2026-03-11,4100000.0,Gregg,Whitney,32.718935,-117.233647,924 Scott St,...,NaN,92106,Compass,NaN,5662.0,NaN,924 Scott St,2026-02,6.0475,True

#### Making Sure that Flag Works as Intended

In [52]:
listings[listings["ListingKey"] == 1154142014]["ListingContractDate"]

1063   2026-02-26
Name: ListingContractDate, dtype: datetime64[ns]

In [53]:
listings[listings["ListingKey"] == 1154142014]["PurchaseContractDate"]

1063   2026-02-02
Name: PurchaseContractDate, dtype: datetime64[ns]

#### Continuing Check

In [54]:
listings["purchase_after_close_flag"] = listings["CloseDate"] < listings["PurchaseContractDate"]

In [55]:
listings["negative_timeline_flag"] = (listings["listings_after_close_flag"] == True) | (listings["purchase_after_close_flag"] == True)

#### Flagging in Sold Dataset

In [56]:
sold["listings_after_close_flag"] = sold["ListingContractDate"] > sold["PurchaseContractDate"]

In [57]:
sold["purchase_after_close_flag"] = sold["CloseDate"] < sold["PurchaseContractDate"]

In [58]:
sold["negative_timeline_flag"] = (sold["listings_after_close_flag"] == True) | (sold["purchase_after_close_flag"] == True)

### Geographic Data Checks

In [59]:
listings["no_coordinates"] = (listings["Longitude"].isna()) | (listings["Latitude"].isna())
sold["no_coordinates"] = (sold["Longitude"].isna()) | (sold["Latitude"].isna())

In [60]:
listings[listings["no_coordinates"] == True]

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,year_month,rate_30yr_fixed,listings_after_close_flag,purchase_after_close_flag,negative_timeline_flag,no_coordinates
281,1499000.0,1154513655,Brent@HaywoodRealtyGroup.net,NaT,NaN,Brent,Haywood,NaN,NaN,580 582 South Grade,...,NaN,NaN,NaN,580 582 South Grade,2026-02,6.0475,False,False,False,True
589,5850000.0,1154281396,staplesgannaway@compass.com,NaT,NaN,NaN,Staples Gannaway ...,NaN,NaN,0 Palou 9 NW of Casanova,...,NaN,6000.0,NaN,0 Palou 9 NW of Casanova,2026-02,6.0475,False,False,False,True
935,799000.0,1154149158,anly@sbcglobal.net,NaT,NaN,An Chi,Ly,NaN,NaN,417 417 Mystic Ln,...,160.0,4127.0,NaN,417 417 Mystic Ln,2026-02,6.0475,False,False,False,True
1082,11995000.0,1154141428,realestate92037@gmail.com,NaT,NaN,Ross,Clark,NaN,NaN,7111 Encelia,...,NaN,73180.0,NaN,7111 Encelia,2026-02,6.0475,False,False,False,True
1230,955000.0,1154092771,karen.smith@tripointehomes.com,NaT,NaN,Karen,Smith,NaN,NaN,684 Meadowood St Lot 391 Lot 391,...,208.0,NaN,NaN,684 Meadowood St Lot 391 Lot 391,2026-02,6.0475,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96814,1069950.0,1158408435,NaN,NaT,NaN,Mark,Schultz,NaN,NaN,14009 Lilah Lane,...,484.0,NaN,NaN,14009 Lilah Lane,2026-05,6.4425,False,False,False,True
96860,934950.0,1157413891,NaN,NaT,NaN,Mark,Schultz,NaN,NaN,14015 Lilah Lane,...,484.0,NaN,NaN,14015 Lilah Lane,2026-05,6.4425,False,False,False,True
96861,939950.0,1157411991,NaN,NaT,NaN,Mark,Schultz,NaN,NaN,14003 Lilah,...,484.0,NaN,NaN,14003 Lilah,2026-05,6.4425,False,False,False,True
96871,2150000.0,1156787991,NaN,NaT,NaN,Kim,Sanner,NaN,NaN,3742 Mt. Diablo Blvd #2A WOODHAVEN 2A,...,580.0,0.0,NaN,3742 Mt. Diablo Blvd #2A WOODHAVEN 2A,2026-05,6.4425,False,False,False,True
96881,13999999.0,1153102507,NaN,2026-06-15,14500000.0,Heather,Rocha,NaN,NaN,5516 LA CRESCENTA,...,NaN,168577.0,NaN,5516 LA CRESCENTA,2026-05,6.4425,True,False,True,True

In [61]:
listings["sentinel_null_coordinates"] = (listings["Longitude"] == 0) | (listings["Latitude"] == 0)
sold["sentinel_null_coordinates"] = (sold["Longitude"] == 0) | (sold["Latitude"] == 0)

In [62]:
listings["invalid_longitude"] = listings["Longitude"] > 0
sold["invalid_longitude"] = sold["Longitude"] > 0

California longitudes should always be negative.

### Dataset Adjustments

In [63]:
len(listings)

96885

#### Removing flagged entries

In [64]:
listings_condition = (
    (listings["listings_after_close_flag"] == True) |
    (listings["purchase_after_close_flag"] == True) |
    (listings["negative_timeline_flag"] == True) |
    (listings["no_coordinates"] == True) |
    (listings["sentinel_null_coordinates"] == True) |
    (listings["invalid_longitude"] == True)
)

In [65]:
listings = listings[~listings_condition]

#### Updated Row Count

In [66]:
len(listings)

95695

In [67]:
len(sold)

60907

#### Removing Flagged Entries

In [68]:
sold_condition = (
    (sold["listings_after_close_flag"] == True) |
    (sold["purchase_after_close_flag"] == True) |
    (sold["negative_timeline_flag"] == True) |
    (sold["no_coordinates"] == True) |
    (sold["sentinel_null_coordinates"] == True) |
    (sold["invalid_longitude"] == True)
)

In [69]:
sold = sold[~sold_condition]

#### Updated Row Count

In [70]:
len(sold)

60375

### Dropping Repetitive Columns

In [71]:
listings = listings.loc[:, ~listings.columns.str.endswith(".1")]

In [72]:
listings.columns

Index(['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency',
       'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor',
       'TaxAnnualAmount', 'CountyOrParish', 'MlsStatus', 'ElementarySchool',
       'AttachedGarageYN', 'ParkingTotal', 'BuilderName', 'PropertySubType',
       'LotSizeAcres', 'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt',
       'StreetNumberNumeric', 'ListingId', 'BathroomsTotalInteger', 'City',
       'TaxYear', 'BuildingAreaTotal', 'BedroomsTotal',
       'ContractStatusChangeDate', 'ElementarySchoolDistrict',
       'CoBuyerAgentFirstName', 'PurchaseContractDate', 'ListingContractDate',
       'BelowGradeFinishedArea', 'BusinessType', 'StateOrProvince',
       'CoveredSpaces', 'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories',
       'HighSchool', 'Levels', 'LotSizeDimensions', 'LotSizeArea',
       'MainLevelBedrooms', 'NewConstructionYN', 'GarageSpaces',
       'HighSchoolDistrict', 'PostalCode', 'AssociationFee',
       'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict', 'year_month',
       'rate_30yr_fixed', 'listings_after_close_flag',
       'purchase_after_close_flag', 'negative_timeline_flag', 'no_coordinates',
       'sentinel_null_coordinates', 'invalid_longitude'],
      dtype='object')

### Flagging Invalid Numeric Columns

In [73]:
listings["invalid_numeric"] = listings[
    (listings["DaysOnMarket"] < 0) |
    (listings["LivingArea"] < 0) |
    (listings["ClosePrice"] < 0) |
    (listings["BathroomsTotalInteger"] < 0) |
    (listings["BedroomsTotal"] < 0) |
    (listings["LivingArea"] < 0)
].any(axis=1)

C:\Users\mukun\AppData\Local\Temp\ipykernel_31584\3886972215.py:8: FutureWarning: 'any' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).any() instead.
  ].any(axis=1)
C:\Users\mukun\AppData\Local\Temp\ipykernel_31584\3886972215.py:8: FutureWarning: 'any' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).any() instead.
  ].any(axis=1)
C:\Users\mukun\AppData\Local\Temp\ipykernel_31584\3886972215.py:8: FutureWarning: 'any' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).any() instead.
  ].any(axis=1)

In [74]:
sold["invalid_numeric"] = sold[
    (sold["DaysOnMarket"] < 0) |
    (sold["LivingArea"] < 0) |
    (sold["ClosePrice"] < 0) |
    (sold["BathroomsTotalInteger"] < 0) |
    (sold["BedroomsTotal"] < 0) |
    (sold["LivingArea"] < 0)
].any(axis=1)

C:\Users\mukun\AppData\Local\Temp\ipykernel_31584\3783981030.py:8: FutureWarning: 'any' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).any() instead.
  ].any(axis=1)
C:\Users\mukun\AppData\Local\Temp\ipykernel_31584\3783981030.py:8: FutureWarning: 'any' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).any() instead.
  ].any(axis=1)
C:\Users\mukun\AppData\Local\Temp\ipykernel_31584\3783981030.py:8: FutureWarning: 'any' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).any() instead.
  ].any(axis=1)

In [75]:
len(listings)

95695

In [76]:
listings_numeric_condition = listings["invalid_numeric"] == True

In [77]:
listings = listings[~listings_numeric_condition]

In [78]:
len(listings)

95693

In [79]:
len(sold)

60375

In [80]:
sold_numeric_condition = sold["invalid_numeric"] == True

In [81]:
sold = sold[~sold_numeric_condition]

In [82]:
len(sold)

60371

### Exporting Cleaned and Prepared Dataset

Now that I made sure that entries with invalid entries or null values in important columns are removed, I am ready to export the datasets as csvs for further analysis.

In [83]:
listings.to_csv("cleaned_listings.csv", index=False)

In [84]:
sold.to_csv("cleaned_sold.csv", index=False)