# EDA for Sold and Listings Datasets

In [14]:
import pandas as pd

In [15]:
sold = pd.read_csv("sold_residential.csv")
listing = pd.read_csv("listings_residential.csv")

C:\Users\mukun\AppData\Local\Temp\ipykernel_1492\1384943678.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sold = pd.read_csv("sold_residential.csv")
C:\Users\mukun\AppData\Local\Temp\ipykernel_1492\1384943678.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  listing = pd.read_csv("listings_residential.csv")

## Checking Sold Dataset

In [33]:
sold.columns

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName'],
      dtype='object')

In [16]:
sold.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName
0,BayEast,Oakland,Carpet,NaN,NaN,NaN,False,1210000.0,1155025463,mike.swiderski@cbnorcal.com,...,NaN,False,2.0,NaN,94598,NaN,27600.0,NaN,CRMLS,CRMLS_BMLS
1,Newport,Newport,"Tile,Wood",True,NaN,NaN,False,3150000.0,1154998305,casey@caseyoconnorgroup.com,...,1.0,True,1.0,Newport Mesa Unified,92625,0.0,3540.0,NaN,CRMLS,CRMLS_CRM
2,Mlslistings,Mlslistings,NaN,False,NaN,NaN,NaN,NaN,1154943263,ben@strockrealestate.com,...,NaN,False,2.0,Other,95032,NaN,10454.0,NaN,CRMLS,CRMLS_MLSL
3,NorthSanDiegoCounty,NorthSanDiegoCounty,Laminate,False,NaN,NaN,False,649999.0,1154868125,listings@bottrellteam.com,...,NaN,NaN,1.0,San Diego Unified,92105,0.0,5500.0,NaN,CRMLS,CRMLS_CRP
4,SanDiego,PacificSouthwest,NaN,True,NaN,NaN,False,1191000.0,1154717602,cesmeralda1992@gmail.com,...,NaN,NaN,2.0,Other,91913,135.0,4356.0,NaN,CRMLS,CRMLS_CRP

In [21]:
sold["PropertyType"].unique()

array(['Residential'], dtype=object)

I printed the first 5 rows to see if the dataset was properly loaded. I also checked to see if my filter in the previous week worked to only include residential properties.

## Null Value Analysis

In [23]:
sold.isnull().sum()

BuyerAgentAOR                    6439
ListAgentAOR                       17
Flooring                        22256
ViewYN                           5175
WaterfrontYN                    60861
                                ...
AssociationFee                  13469
LotSizeSquareFeet                4369
MiddleOrJuniorSchoolDistrict    60907
OriginatingSystemName               0
OriginatingSystemSubName            0
Length: 80, dtype: int64

In [17]:
perc_null = sold.isnull().sum()/len(sold)
perc_null

BuyerAgentAOR                   0.105719
ListAgentAOR                    0.000279
Flooring                        0.365410
ViewYN                          0.084966
WaterfrontYN                    0.999245
                                  ...
AssociationFee                  0.221140
LotSizeSquareFeet               0.071732
MiddleOrJuniorSchoolDistrict    1.000000
OriginatingSystemName           0.000000
OriginatingSystemSubName        0.000000
Length: 80, dtype: float64

perc_null calculates the percentage of values that are null for each column in the sold dataset.

In [18]:
perc_null[perc_null > 0.9]

WaterfrontYN                    0.999245
BasementYN                      0.980626
FireplacesTotal                 1.000000
AboveGradeFinishedArea          1.000000
TaxAnnualAmount                 1.000000
BuilderName                     0.950613
TaxYear                         1.000000
BuildingAreaTotal               0.927315
ElementarySchoolDistrict        1.000000
CoBuyerAgentFirstName           0.902326
BelowGradeFinishedArea          0.993137
BusinessType                    1.000000
CoveredSpaces                   1.000000
LotSizeDimensions               0.951730
MiddleOrJuniorSchoolDistrict    1.000000
dtype: float64

The above columns represent columns where over 90% of the values are null.

## Numeric Distribution Summary for Key Columns

In [26]:
sold["ClosePrice"].describe()

count    6.090700e+04
mean     1.220681e+06
std      6.629136e+06
min      5.000000e+03
25%      5.750000e+05
50%      8.250000e+05
75%      1.315000e+06
max      7.960000e+08
Name: ClosePrice, dtype: float64

In [27]:
sold["LivingArea"].describe()

count    60883.000000
mean      1888.463611
std        996.620189
min          0.000000
25%       1260.000000
50%       1666.000000
75%       2259.000000
max      28502.000000
Name: LivingArea, dtype: float64

In [29]:
sold["DaysOnMarket"].describe()

count    60907.000000
mean        40.965390
std         58.463984
min        -39.000000
25%          7.000000
50%         18.000000
75%         51.000000
max       2177.000000
Name: DaysOnMarket, dtype: float64

## Checking Listings Dataset

In [34]:
listing.columns

Index(['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency',
       'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor',
       'TaxAnnualAmount', 'CountyOrParish', 'PropertyType.1', 'MlsStatus',
       'ElementarySchool', 'ListAgentFirstName.1', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1',
       'StreetNumberNumeric', 'LivingArea.1', 'ListingId',
       'BathroomsTotalInteger', 'City', 'TaxYear', 'BuildingAreaTotal',
       'BedroomsTotal', 'ContractStatusChangeDate', 'Longitude.1',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'Latitude.1', 'ListPrice.1', 'StateOrProvince',
       'CoveredSpaces', 'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories',
       'HighSchool', 'Levels', 'ListAgentLastName.1', 'CloseDate.1',
       'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1'],
      dtype='object')

In [30]:
listing.head()

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,699000.0,1155102284,realtorck123@gmail.com,NaN,NaN,KWOK,CHOO,34.157413,-118.122500,1348 E Orange Grove Boulevard 4,...,1.0,False,2.0,Pasadena Unified,91104,NaN,456.0,13985.0,NaN,1348 E Orange Grove Boulevard 4
1,2300000.0,1155098526,Marilyn@ocluxuryhomes.com,NaN,NaN,Marilyn,Ryder,33.476010,-117.701575,24444 Alta Vista Drive 19,...,1.0,False,2.0,Capistrano Unified,92629,NaN,891.0,0.0,NaN,24444 Alta Vista Drive 19
2,1100000.0,1155097469,ryan.bass@camoves.com,NaN,NaN,Ryan,Bass,32.807548,-117.020585,6849 Ballinger Avenue,...,3.0,NaN,2.0,San Diego Unified,92119,NaN,0.0,7200.0,NaN,6849 Ballinger Avenue
3,550000.0,1155097291,soldbycrystalhoggard@gmail.com,NaN,NaN,CRYSTAL,HOGGARD,34.247686,-117.321376,330 Canyon Drive,...,2.0,False,0.0,Rim of the World,92322,NaN,0.0,107526.0,NaN,330 Canyon Drive
4,705000.0,1155096363,TDillon@RealtyExecutivesDillon.com,NaN,NaN,Terri,Dillon,32.726242,-117.034517,1905 El Dora Street,...,NaN,NaN,1.0,Lemon Grove,91945,NaN,0.0,7200.0,NaN,1905 El Dora Street

In [35]:
listing["PropertyType"].unique()

array(['Residential'], dtype=object)

## Null Value Analysis

In [36]:
sold.isnull().sum()

BuyerAgentAOR                    6439
ListAgentAOR                       17
Flooring                        22256
ViewYN                           5175
WaterfrontYN                    60861
                                ...
AssociationFee                  13469
LotSizeSquareFeet                4369
MiddleOrJuniorSchoolDistrict    60907
OriginatingSystemName               0
OriginatingSystemSubName            0
Length: 80, dtype: int64

In [37]:
listings_perc_null = sold.isnull().sum()/len(listing)
listings_perc_null

BuyerAgentAOR                   0.066460
ListAgentAOR                    0.000175
Flooring                        0.229716
ViewYN                          0.053414
WaterfrontYN                    0.628178
                                  ...
AssociationFee                  0.139020
LotSizeSquareFeet               0.045095
MiddleOrJuniorSchoolDistrict    0.628653
OriginatingSystemName           0.000000
OriginatingSystemSubName        0.000000
Length: 80, dtype: float64

In [38]:
listings_perc_null[listings_perc_null > 0.90]

Series([], dtype: float64)

There are no columns with more than 90% missing values in the listings dataset.

## Numeric Distribution Summary for Key Columns

In [39]:
listing["OriginalListPrice"].describe()

count    8.659000e+03
mean     1.425841e+06
std      1.138893e+06
min      9.500000e+04
25%      5.950000e+05
50%      9.950000e+05
75%      1.675000e+06
max      6.750000e+07
Name: OriginalListPrice, dtype: float64